name: Build
on:
  push:
    branches: [naive]
    paths-ignore: [README.md]
  release:
    types: [published]
defaults:
  run:
    shell: bash
jobs:
  build_caddy_with_naive:
    runs-on: ubuntu-22.04
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD
      
